# Generated by Django 5.2.10 on 2026-03-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_month', models.DateField(help_text='First month they contributed (YYYY-MM-01)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField(help_text='First month this target applies (YYYY-MM-01)')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(help_text='M-Pesa transaction code', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(help_text='Date & time from the SMS')),
                ('contribution_month', models.DateField(help_text='Month this payment counts for (YYYY-MM-01)')),
                ('sms_text', models.TextField(blank=True, help_text='Original SMS pasted by admin')),
                ('sms_source', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cytonn', 'Cytonn'), ('manual', 'Manual entry')], default='mpesa', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chama.member')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'unique_together': {('member', 'contribution_month')},
            },
        ),
    ]
